apiVersion: apps/v1
kind: Deployment
metadata:
    name: auth-mongo
spec:
    replicas: 1
    selector:
        matchLabels:
            app: auth-mongo
    template:
        metadata:
            labels:
                app: auth-mongo
        spec:
            containers:
                - name: mongo
                  image: mongo:5.0
                  env:
                      - name: MONGO_INITDB_DATABASE
                        value: "authdb"
                  volumeMounts:
                      - name: mongo-data
                        mountPath: /data/db
            volumes:
                - name: mongo-data
                  persistentVolumeClaim:
                      claimName: mongo-pvc
---
apiVersion: v1
kind: Service
metadata:
    name: auth-mongo
spec:
    selector:
        app: auth-mongo
    ports:
        - protocol: TCP
          port: 27017
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: mongo-pvc
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 1Gi
